#!/bin/zsh
set -euo pipefail

: "${FARFIELD_CLOUDFLARED_BIN:?FARFIELD_CLOUDFLARED_BIN is required}"
: "${FARFIELD_TUNNEL_NAME:?FARFIELD_TUNNEL_NAME is required}"
: "${FARFIELD_CLOUDFLARED_CONFIG:?FARFIELD_CLOUDFLARED_CONFIG is required}"
: "${FARFIELD_CLOUDFLARED_CERT:?FARFIELD_CLOUDFLARED_CERT is required}"

export TUNNEL_DNS_RESOLVER_ADDRS="${TUNNEL_DNS_RESOLVER_ADDRS:-1.1.1.1:53,1.0.0.1:53}"

exec "$FARFIELD_CLOUDFLARED_BIN" \
  --config "$FARFIELD_CLOUDFLARED_CONFIG" \
  --origincert "$FARFIELD_CLOUDFLARED_CERT" \
  tunnel run "$FARFIELD_TUNNEL_NAME"
